---
swagger: "2.0"
info:
  description: "이 페이지는 동의대학교 응용소프트웨어학과 Dcloud팀에서 만든 Proxmox을 이용한 laas 서비스 운영페이지에 대한 API 설명서입니다."
  version: "0.0.1"
  title: "D Cloud Platform"
  contact:
    email: "lyw514549@gmail.com"
host: "https://phpproject.powerinmd.com"
basePath: "/api"
tags:
- name: "Auth"
  description: "인증할때 쓰이는 API들"
- name: "Proxmox"
  description: "서버에 있는 정보를 불려올때 쓰는 API"
schemes:
- "https"
paths:
  /singup:
    post:
      tags:
      - "Auth"
      summary: "회원가입 API"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "email"
        in: "formData"
        description: "이메일"
        type: "string"
      - name: "name"
        in: "formData"
        description: "학생들 이름"
        required: false
        type: "string"
      - name: "password"
        in: "formData"
        description: "패스워드 추후 암호화가 되어 DB에 저장됨"
        required: false
        type: "string"
      - name: "student_class"
        in: "formData"
        description: "학생 학과"
        required: false
        type: "string"
      - name: "student_ID"
        in: "formData"
        description: "학생 학번"
        required: false
        type: "string"
      - name: "phone_number"
        in: "formData"
        description: "학생 전화번호"
        required: false
        type: "string"
      responses:
        201:
          description: "성공하면 자신이 입력한 내용을 다시 반환함 성공코드:20000"
          schema:
            $ref: "#/definitions/Sinup"
        503:
          description: "중복된 사항이 있으면 Message로 알려줌 오류코드:51103"
          schema:
            $ref: "#/definitions/same"

  /login:
    post:
      tags:
      - "Auth"
      summary: "로그인할때 쓰는 API"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "email"
        in: "formData"
        description: "이메일"
        type: "string"
      - name: "password"
        in: "formData"
        description: "패스워드"
        required: false
        type: "string"      
      responses:
        200:
          description: "성공하면 커스텀한 JWT를 반환함"
          schema:
            $ref: "#/definitions/login_succes"
        503:
          description: "계정또는 비번이 틀리면 오류코드 반환. 오류코드: 51102"
          schema:
            $ref: "#/definitions/same"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "https://petstore.swagger.io/oauth/authorize"
    flow: "implicit"
    scopes:
      read:pets: "read your pets"
      write:pets: "modify pets in your account"
definitions:
 Sinup:
  type: "object"
  properties:
    Code:
      type: "string"
    message:
      type: "object"
      properties:
        email:
          type: "string"
        name:
          type: "string"
        password:
          type: "string"
        student_class:
          type: "string"
        student_ID:
          type: "string"
        phone_number:
          type: "string"
 same:
   type: "object"
   properties:
    Code:
      type: "string"
    message:
      type: "string"
 login_succes:
   type: "object"
   properties:
    Code:
      type: "string"
    Access:
      type: "string"





externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
